add http protocol if user website is missing it
PrimalHQ/primal-android-app pull request #108
Opened 2024-03-08 14:56 UTC by davotoula

2024-03-12 12:35 UTC, AleksandarIlic requested changes
Thanks for the PR. I had just two minor comments.

2024-03-12 12:35 UTC, AleksandarIlic commented on app/src/main/kotlin/net/primal/android/profile/details/ProfileDetailsScreen.kt
> +            val websiteWithProtocol = if (state.profileDetails.website.startsWith("http", true))
Please use named arguments in startsWith(). It will be more readable when looking at the code outside of the IDE.

2024-03-12 12:35 UTC, AleksandarIlic commented on app/src/main/kotlin/net/primal/android/profile/details/ProfileDetailsScreen.kt
> +                "http://" + state.profileDetails.website
I would prefer "https://". 

And please remove the comment above, since the code will be self explanatory when we use `https`.

2024-03-12 20:09 UTC, davotoula commented
changes done

2024-03-13 14:36 UTC, AleksandarIlic approved these changes

2024-03-13 14:37 UTC, merged