Feature: explore feeds tab
PrimalHQ/primal-android-app pull request #186
Opened 2024-10-01 11:06 UTC by markocic

2024-10-01 14:41 UTC, AleksandarIlic requested changes
All the comments are just further improvements of already great implementation.

2024-10-01 14:41 UTC, AleksandarIlic commented on app/src/main/kotlin/net/primal/android/explore/home/feeds/ExploreFeedsViewModel.kt
> +class ExploreFeedsViewModel @AssistedInject constructor(
No need for assisted injection here.

There is `ActiveAccountStore` which always reflect the current active account in the app. You can add it as regular constructor injection and then use in the viewModel following function `activeAccountStore.activeUserId()`

2024-10-01 14:41 UTC, AleksandarIlic commented on app/src/main/kotlin/net/primal/android/explore/home/feeds/ExploreFeeds.kt
> +                    FeedSpecKind.Notes -> mutableStateOf(state.userNoteFeeds.map { it.spec }.contains(spec))
Can we map the feed to feedSpec directly in ViewModel and just check here if it's contained in that list?

2024-10-01 14:41 UTC, AleksandarIlic commented on app/src/main/kotlin/net/primal/android/explore/home/feeds/ExploreFeedsViewModel.kt
> +        observeUserNoteFeeds()
Any particular reason why feeds are separated? You could observe all feeds at once since we are checking feedSpec only, and they are unique across any feed.

2024-10-01 14:41 UTC, AleksandarIlic commented on app/src/main/kotlin/net/primal/android/explore/home/feeds/ExploreFeeds.kt
> +        dvmFeedToShow?.let {
No need for two variables. You could have a `var selectedDvmFeed` which would be `null` if nothing is selected and if `not null` then you show the bottom sheet.

2024-10-01 14:41 UTC, AleksandarIlic commented on app/src/main/kotlin/net/primal/android/explore/home/feeds/ExploreFeeds.kt
> +    val handleCloseBottomSheet: () -> Unit = {
Did you know you could have here something like this?
``` kotlin
fun closeBottomSheet() {
    scope.launch {
        sheetState.hide()
    }.invokeOnCompletion {
        if (!sheetState.isVisible) {
            onDismissRequest()
        }
    }
}
```

2024-10-01 14:41 UTC, AleksandarIlic commented on app/src/main/kotlin/net/primal/android/explore/home/feeds/ExploreFeedsContract.kt
> +        val userNoteFeeds: List<FeedUi> = emptyList(),
As already mentioned on the viewModel, this could probably be merged into single list and mapped to feedSpec.

2024-10-01 14:41 UTC, AleksandarIlic commented on app/src/main/kotlin/net/primal/android/feeds/item/DvmFeedListItem.kt
> +                        fontWeight = FontWeight.W400,
Better to use the named font weight to be consistent with the rest of the app. In this example, `FontWeight.Normal`.

2024-10-01 14:41 UTC, AleksandarIlic commented on app/src/main/kotlin/net/primal/android/feeds/item/DvmFeedListItem.kt
> +}
SUB, PAID and FREE should probably go to `strings.xml`?

2024-10-01 14:41 UTC, AleksandarIlic commented on app/src/main/kotlin/net/primal/android/feeds/item/DvmFeedListItem.kt
> +        style = AppTheme.typography.bodySmall.copy(fontSize = TextUnit(10f, TextUnitType.Sp)),
I think there is a `fontSize` argument here in `Text`, you don't have to make a copy of a style.

2024-10-01 14:41 UTC, AleksandarIlic commented on app/src/main/kotlin/net/primal/android/feeds/item/DvmFeedListItemViewModel.kt
> +            // TODO(marko): handle zap
No need to add the name. We can always see who was the author with `git blame`.

2024-10-01 14:41 UTC, AleksandarIlic commented on app/src/main/kotlin/net/primal/android/feeds/repository/FeedsRepository.kt
> +    suspend fun persistAllLocalUserFeeds(userId: String) {
You could extract the logic for single FeedSpecKind into
`persistLocalUserFeeds(userId: String, specKind: FeedSpecKind)`

and then in `persistAllLocalUserFeeds(userId: String)` you could just say:

```kotlin
suspend fun persistAllLocalUserFeeds(userId: String) {
    persistLocalUserFeeds(userId = userId, specKind = FeedSpecKind.Reads)
    persistLocalUserFeeds(userId = userId, specKind = FeedSpecKind.Notes)
}
```

2024-10-01 14:41 UTC, AleksandarIlic commented on app/src/main/kotlin/net/primal/android/feeds/repository/FeedsRepository.kt
> +    suspend fun persistGivenUserFeeds(feeds: List<Feed>, specKind: FeedSpecKind) {
In some repositories we use `ActiveAccountStore` directly and in some we pass `userId` with every function. This is something that we'll need to clean in the future and decided on it's place. That was my mistake for not setting this up properly.

In the meantime, we should at least have the same standard within the a class. We should either remove the `ActiveAccountStore` dependency from this repository or actively use it in all functions where needed without extra `userId` arguments.

2024-10-03 19:48 UTC, markocic commented on app/src/main/kotlin/net/primal/android/feeds/item/DvmFeedListItem.kt
> +        style = AppTheme.typography.bodySmall.copy(fontSize = TextUnit(10f, TextUnitType.Sp)),
Default `line height` is a bit too much here. I wanted to get the `line height` from `bodySmall` but with a slightly smaller font size.

2024-10-03 19:51 UTC, markocic commented on app/src/main/kotlin/net/primal/android/feeds/item/DvmFeedListItemViewModel.kt
> +            // TODO(marko): handle zap
Name indicates for whom this TODO is meant for. I use this convention as a reminder when I know that I will be completing this feature in future PRs but not right now. I could look for other kinds of reminders if needed.

2024-10-03 19:58 UTC, markocic commented on app/src/main/kotlin/net/primal/android/feeds/repository/FeedsRepository.kt
> +    suspend fun persistGivenUserFeeds(feeds: List<Feed>, specKind: FeedSpecKind) {
I agree. We could discuss pros and cons of both approaches in the next meeting and I will update the class accordingly.

2024-10-04 10:01 UTC, AleksandarIlic approved these changes
Great work!

2024-10-04 10:02 UTC, merged