Refactor user badge component
PrimalHQ/primal-android-app pull request #259
Opened 2024-12-19 02:22 UTC by mehmedalijaK

2024-12-19 16:32 UTC, markocic requested changes
Very good! One more thing that should be changed along with comments is that every usage of `NostrUserText` should be given `legendaryCustomization` if there is also an `UniversalAvatarThumbnail` with `legendaryCustomization`. Examples of this can be seen in `MutedUserListItem.kt:129` and `NotificationListItem.kt:406`. Might be the only two places, if I haven't missed any.

2024-12-19 16:32 UTC, markocic commented on app/src/main/kotlin/net/primal/android/premium/legend/custimization/LegendaryProfileCustomizationScreen.kt
> +                    if (customBadge == true) {
This could be simplified by setting `customBadge` inside `LegendaryCustomization`.

```kt
authorLegendaryCustomization = LegendaryCustomization(customBadge = customBadge, legendaryStyle = selectedStyle)
```

This will result in the same behavior but more readable code.

2024-12-19 16:32 UTC, markocic commented on app/src/main/kotlin/net/primal/android/core/compose/NostrUserText.kt
> +    authorLegendaryCustomization: LegendaryCustomization? = null,
Nitpick: I think `legendaryCustomization` is a better name here since we didn't use `author` prefix on other user-related data.

2024-12-20 00:52 UTC, markocic approved these changes

2024-12-20 08:37 UTC, AleksandarIlic approved these changes
Good work!

2024-12-20 08:38 UTC, merged