Create account feature
PrimalHQ/primal-android-app pull request #40
Opened 2023-09-13 11:14 UTC by nikolalukovic

2023-09-15 10:34 UTC, AleksandarIlic requested changes

2023-09-15 10:34 UTC, AleksandarIlic commented on app/build.gradle.kts
> +        versionName = "0.16.0-feature-create-account-pre-release"
In the future please don't add descriptive suffix. Changes can be described in the RELEASE_NOTES.md.

2023-09-15 10:34 UTC, AleksandarIlic commented on app/src/main/kotlin/net/primal/android/auth/create/api/model/RecommendedFollowsResponse.kt
> +data class Metadata(
Why not using `NostrEvent`?

2023-09-15 10:34 UTC, AleksandarIlic commented on app/src/main/kotlin/net/primal/android/auth/create/api/model/CreateNostrProfileMetadata.kt
> +data class CreateNostrProfileMetadata(
We already have `ContentMetadata` in `nostr.model.content` package. Can it be reused?

2023-09-15 10:34 UTC, AleksandarIlic commented on app/src/main/kotlin/net/primal/android/auth/create/CreateContract.kt
> +        data class AvatarUriChangedEvent(val avatarUri: Uri?) : UiEvent()
Maybe you can store the states inside of the screen composable and only on Next update the `ViewModel`. Or maybe we could also keep everything in the screen and pass the event to view model on final action. The current approach has too many small events which just update the state which probably could be kept inside of the screen.

`mutableStateOf` can be used in Composables with `remember` functions. `rememberSaveable` is good for saving the state across configuration changes as well which we should do in this case.

2023-09-15 10:34 UTC, AleksandarIlic commented on app/src/main/kotlin/net/primal/android/core/compose/PrimalLoadingSpinner.kt
> +fun PrimalLoadingSpinner(
Loading sins have been forgiven. Great catch.

2023-09-15 10:34 UTC, AleksandarIlic commented on app/src/main/kotlin/net/primal/android/networking/primal/PrimalClient.kt
> +class PrimalClient @Inject constructor(
Why changing the name?

2023-09-15 10:34 UTC, AleksandarIlic commented on app/src/main/kotlin/net/primal/android/networking/di/SocketModule.kt
> +    @Named("Upload")
Can we use custom annotations?

2023-09-15 10:34 UTC, AleksandarIlic commented on app/src/main/kotlin/net/primal/android/networking/relays/RelayPool.kt
> +    private var bootstrapRelays = listOf<NostrSocketClient>()
This relays stuff needs to be refactored. We are just adding to much complexity here and needs to be simplified somehow. I don't have any ideas at the moment, I'll have to think about it how to approach this.

The more complexity goes up the more chances are that something can be broken, misunderstood or misused in the future. That is the main concern.

2023-09-15 10:34 UTC, AleksandarIlic commented on app/src/main/kotlin/net/primal/android/networking/sockets/NostrSocketClient.kt
> +class NostrSocketClient @Inject constructor(
Why add? This was intentionally left so we couldn't instantiate this class with DI.

2023-09-15 10:34 UTC, AleksandarIlic commented on app/src/main/kotlin/net/primal/android/nostr/model/content/ContentMetadata.kt
> +fun ContentMetadata.userNameUiFriendly(pubkey: String): String {
This introduces the same business logic in two places now. It already exists in `ProfileMetadata`. The business logic of user|author friendly names should be only in one place.

The solution is probably that both `ContentMetadata` and `ProfileMetadata` use that business logic.

2023-09-15 10:34 UTC, AleksandarIlic commented on app/src/main/kotlin/net/primal/android/nostr/notary/NostrNotary.kt
> +    fun signFirstContactNostrEvent(
Why can't we reuse the default one? The same question applies for `signInitialContactsNostrEvent`?

2023-09-15 10:34 UTC, AleksandarIlic commented on app/src/main/kotlin/net/primal/android/auth/create/compose/CreateScreen.kt
> +fun CreateScreen(
I have to look into this code from IDE in more details. Can't do it today.

2023-09-20 14:47 UTC, nikolalukovic commented on app/src/main/kotlin/net/primal/android/auth/create/api/model/RecommendedFollowsResponse.kt
> +data class Metadata(
It didn't cross my mind to use it, lul. I'll switch to it.

2023-09-20 14:48 UTC, nikolalukovic commented on app/src/main/kotlin/net/primal/android/auth/create/api/model/CreateNostrProfileMetadata.kt
> +data class CreateNostrProfileMetadata(
It didn't cross my mind to use it, lul. I'll switch to it.

2023-09-20 14:49 UTC, nikolalukovic commented on app/src/main/kotlin/net/primal/android/networking/sockets/NostrSocketClient.kt
> +class NostrSocketClient @Inject constructor(
Forgot to remove it. Will remove.

2023-09-20 14:51 UTC, nikolalukovic commented on app/src/main/kotlin/net/primal/android/networking/primal/PrimalClient.kt
> +class PrimalClient @Inject constructor(
The reasoning behind it was that we're using two instances of it. One to consume the API and the other to consume the UPLOAD

2023-09-20 14:55 UTC, nikolalukovic commented on app/src/main/kotlin/net/primal/android/nostr/notary/NostrNotary.kt
> +    fun signFirstContactNostrEvent(
We're not logged in when this has to be used.

2023-09-20 15:03 UTC, nikolalukovic commented on app/src/main/kotlin/net/primal/android/auth/create/CreateContract.kt
> +        data class AvatarUriChangedEvent(val avatarUri: Uri?) : UiEvent()
👍🏻 I'll change it

2023-09-20 15:06 UTC, nikolalukovic commented on app/src/main/kotlin/net/primal/android/nostr/model/content/ContentMetadata.kt
> +fun ContentMetadata.userNameUiFriendly(pubkey: String): String {
It feels wrong to use `ProfileMetadata` considering it's a domain model bound to db. While using `ContentMetadata` here feels more natural considering it's just a transient API consumption model.

2023-09-22 10:38 UTC, AleksandarIlic commented on app/src/main/kotlin/net/primal/android/nostr/notary/NostrNotary.kt
> +    fun signFirstContactNostrEvent(
Why can't we login the user first and then perform all other operations? In case something goes wrong, we can rollback/logout or provide some other fallback solution.

2023-09-22 10:41 UTC, AleksandarIlic commented on app/src/main/kotlin/net/primal/android/nostr/model/content/ContentMetadata.kt
> +fun ContentMetadata.userNameUiFriendly(pubkey: String): String {
I agree. If the business logic is in more than one place it can cause maintenance problems in the future.

We should put it in one place and make some wrappers/helpers around ti for `ContentMetadata` and `ProfileMetadata`.

2023-09-22 10:42 UTC, AleksandarIlic commented on app/src/main/kotlin/net/primal/android/networking/primal/PrimalClient.kt
> +class PrimalClient @Inject constructor(
Yes, but upload is still some kind of API.

2023-09-25 14:49 UTC, AleksandarIlic approved these changes

2023-09-25 14:53 UTC, merged