Initial edit account view
PrimalHQ/primal-android-app pull request #44
Opened 2023-09-25 19:03 UTC by nikolalukovic

2023-09-26 13:40 UTC, AleksandarIlic requested changes
Overall looks very good. Just few minor things.

2023-09-26 13:40 UTC, AleksandarIlic commented on app/src/main/kotlin/net/primal/android/navigation/PrimalAppNavigation.kt
> +            editProfile(route = "edit-profile", navController = navController)
edit_profile

2023-09-26 13:40 UTC, AleksandarIlic commented on app/src/main/kotlin/net/primal/android/profile/details/ProfileContract.kt
> +        val isCurrentUser: Boolean,
isActiveUser

2023-09-26 13:40 UTC, AleksandarIlic commented on app/src/main/kotlin/net/primal/android/profile/details/ProfileScreen.kt
> +            })
You either need to show Follow/Unfollow buton or Edit Profile. If/else should be enough.

2023-09-26 13:40 UTC, AleksandarIlic commented on app/src/main/kotlin/net/primal/android/profile/edit/EditProfileScreen.kt
> +            .navigationBarsPadding()
Remove systemBarsPadding() and navigationsBarsPadding(). It's causing padding issues.

2023-09-26 13:40 UTC, AleksandarIlic commented on app/src/main/kotlin/net/primal/android/profile/edit/EditProfileContract.kt
> +fun EditProfileContract.UiState.toProfileMetadata(): ProfileMetadata {
This shouldn't be in Contract. Move it to viewModel.

2023-09-26 13:40 UTC, AleksandarIlic commented on app/src/main/kotlin/net/primal/android/profile/edit/EditProfileContract.kt
> +    )
We need to make sure that we don't send empty strings. You can use `.ifEmpty { null }` extension function to return null if the fields are not nullables.

2023-09-26 13:40 UTC, AleksandarIlic commented on app/src/main/kotlin/net/primal/android/profile/edit/EditProfileScreen.kt
> +                title = "Edit Profile",
Move to strings.xml.

2023-09-26 13:40 UTC, AleksandarIlic commented on app/src/main/kotlin/net/primal/android/profile/edit/EditProfileViewModel.kt
> +                    avatarUri = it.metadata?.picture?.toUri()
Regarding the situation where we can have both local and remote images.

We could probably update `ProfileMetadata` domain class to have `localPictureUri`, `localBannerUri`, `remotePictureUrl` and `remoteBannerUrl`, and then handle all four potential use cases where appropriate. 

You will also need to update the `ProfileRepository` to fallback to `remote` urls if there are no local one provided.

2023-09-26 16:59 UTC, nikolalukovic commented on app/src/main/kotlin/net/primal/android/profile/edit/EditProfileContract.kt
> +    )
It's a `Uri`. I don't think `Uri` could be created with an empty string. Both are already nullable.

2023-09-27 16:15 UTC, AleksandarIlic commented on app/src/main/kotlin/net/primal/android/profile/edit/EditProfileContract.kt
> +    )
I was referring to String values. For example if there was no nip05 value in metadata and no nip05 value in editor, we would submit nostr event with nip05="".

2023-09-27 16:19 UTC, merged